version: '3'

services:

  # コンテナの名前
  container1:

    # 最新のubuntuのイメージをDocker Hubから取得して利用
    image: ubuntu

    # メインのプロセスとして停止しないコマンドを実行
    entrypoint:
      - tail
      - -f
      - /dev/null

    # # TRY: mongodbを追加してみる
    # # mongoコンテナを内部DNSで参照できるようになる
    # links:
    #   - mongo:mongo

  # # TRY: mongodbを追加してみる
  # # volumeを使っていないので、downするとデータが消える
  # mongo:
  #   image: mongo:3.4
